### ISSUE TITLE
How to write boot.asm as mentioned in the readme.txt of v2.0 ?

### ISSUE THREAD

**Issue by shadowofsmite** [Microsoft/MS-DOS#108]
I have seens [some tutorials](https://github.com/theMike97/OS_Developement) on writing an operating system from scratch, it must exist a boot.asm file to boot the system with qemu for example, so I have read the readme.txt in the version 2.0 and it is said

> 2.  Use your MSDOS development machine and EDLIN or a word processor
>     package to write BOOT.ASM, your bootstrap loader BIOS.ASM and
>     your Format module.

Is it possible to have an idea of what it should looks like ?

Thank You

**Comment by bitcrazed** [comment]
When these versions of MS-DOS were released, each OEM (Original Equipment Manufacturer) was expected to write their own `boot.asm`, because many OEM's computers contained custom hardware and/or required custom boot-up sequences.

If you want to make this code work on a computer of your choosing, you'll need to write a `boot.asm` specific to your chosen hardware platform.
