### ISSUE TITLE
MS-DOS 2.01 / 2.05 / 2.1 / 2.10 / 2.10a / 2.11 / 2.12 / 2.13 / 2.2

### ISSUE THREAD

**Issue by robert-scheck** [Microsoft/MS-DOS#12]
Are there any plans or chances for the source code of MS-DOS 2.01 / 2.05 / 2.1 / 2.10 / 2.10a / 2.11 / 2.12 / 2.13 / 2.2 including the translationed variants? According to the Internet, MS-DOS 2.11 was likely the first version with a German translation…

**Comment by DC7IA** [comment]
Yes, I think we could learn a lot through that code.

**Comment by tuxutku** [comment]
Microsoft can't release the source code before deleting bill gates nudes
it will take them 20 years approximately

**Comment by Matriks404** [comment]
Aren't a lot of these versions OEM specific ones? Microsoft can't release these. They could technically only release the versions that were shipped to manufacturers.

**Comment by darrenstarr** [comment]
@DC7IA I honestly think that there is very little to be learned from this code anymore... at least not anything that wasn't historical like "Hey kids... you wouldn't believe how us old folk used to roll"

DOS was a very very simplistic operating system and it's truly amazing it wasn't cloned more. If I had been 10 years older back then, I might have hacked together my own as it wasn't particularly difficult... well except that compatibility could be difficult to achieve.

These days, even the most simplistic operating system would be based on some form of an ABI that allowed C style calls from applications to the kernel. This in itself is a massive improvement over DOS. The simple fact that DOS did everything using software interrupts stacked on other software interrupts etc... was one of the main reasons DOS was a disaster in architectural terms (at least by modern standards). Consider that every other operating system which was WAY more advanced were so much more advanced because they could just add functions and APIs without difficulty. DOS was a nightmare to maintain. But this was the architecture chosen by the authors of CP/M since in many ways, it was really easy to make single tasking applications that could directly access hardware without fears of semaphores and race conditions.

But as I said, if you wanted to make a new operating system today... starting in a VM which could simulate BIOS instead of UEFI can be helpful. This is because the boot process of UEFI is more complex than DOS as a whole ever was. This isn't a bad thing, it's just a difficult thing to manage.

The next step is to write code to load code. Simply make an OS loader which can read the OS kernel into RAM.

Finally, if you're looking to make something DOS like, put things in fixed memory locations and then just jump to the start of a program's memory. Otherwise, you can make a kernel with proper system calls. Multitasking will still be difficult as it will require understanding how to push and pop full CPU states and how to schedule and handle hardware interrupts (which are actually MMIO operations today).

But to be completely honest, you can make something WAY WAY WAY more advanced today in hours than DOS was after years by using what we've learned since then.

**Comment by bitcrazed** [comment]
Sorry - no plans to publish more recent versions.

**Comment by erkinalp** [comment]
For now.
