### ISSUE TITLE
Document boot process

### ISSUE THREAD

**Issue by dolda2000** [Microsoft/MS-DOS#18]
I think it would make sense to have a small notice somewhere about how the boot process works. What kind of software would have been installed in the boot sector, and is that software included in this repository?

**Comment by darrenstarr** [comment]
I'll be a little bit of a know it all here.

DOS 2.0 added support for hard drives... with the exception of DOSSYM.ASM and DOSSYM211.ASM, there is no reference to how partition operate in DOS 2.0 and later in the code. That said, it is clear that the file boot.asm is missing and unless I'm terribly mistaken, fdisk.asm is missing as well.

That said, it's not needed to properly understand the boot sequence of DOS 1.25 and 2.0 (or most other DOSes) with regards to floppy disks or booting past the hard drive boot sector.

Let me start with a quick clarification... the hard drive boot sector was little more than a simple program which stored 4 distinct entries in a table with "Active, type, start, end" in fixed format. Earlier partition tables employed cylinder, head, sector labelling and later versions employed LBA (or linear addressing in the form of Large Block Addressing). The code on the boot sector was extremely simple, it read the table and found the first active partition. It then read the first sector (or more accurately, the specific sector) mentioned as the start of the partition into memory (I don't recall the specific location, but it was a fixed address) and then executed a JMP to the memory location. That was it. If there was no valid partition marked active, early versions just hung. Later versions introduced things like drop through to allow booting from other drives... but that was MUCH later.

The next thing to see is sys.asm which was the code for the old program sys.com.

If you recall, a major feature that came later in DOS was that format.com could mark a disk as bootable, but it didn't do the boot magic. You'd still have to run sys.com to copy the files to boot the system to the disk. On IBM DOS, these files were IBMBIO.SYS and IBMDOS.SYS (if I recall correctly). For MSDOS, it was IO.SYS and MSDOS.SYS.

You may also recall that simply copying io.sys, msdos.sys and command.com to the disk wasn't good enough to make the disk boot. The BIOS would not read more than a single sector of the disk into memory. That was a total of 512 bytes from the beginning of the disk. If you look at the format of a FAT floppy boot sector (not the same as a HD boot sector). This contained information about how the disk as formatted. This contained the BPB (BIOS parameter block) as well as other metrics. Most importantly though, it contained a VERY SMALL amount of code which would locate the initial boot file and read it into memory... then jump to it... again. In a perfect world, this would be the whole file, but it really only needed to be the first sector of that file... which would then read the rest.

The DOS boot process was extremely location dependent.

The first sector of a disk was boot code and parameters.
The second sector was the start of the file allocation table
After the FAT, there was a verbatim copy of the FAT so that if major corruption occurred, it should still be possible to read the file system.
Finally, there was two sectors dedicated to a fixed sized root directory of the disk. Following all this was the location of IO.SYS and MSDOS.SYS which could not be moved around but had to be written entirely contiguously. This is because the complex logic required to navigate the FAT table of the floppy disk was at least partially in MSDOS.SYS (as you can see more clearly in the DOS 1.25 codebase).

As the code for DOS became more advanced, it became possible to run SYS.COM even on a disk which already had files on it because the newer versions of SYS.COM would clean up the needed sectors similar to how a disk defragmenter works to make room for IO.SYS and MSDOS.SYS.

I hope this was informative. When I was a teenager, I manually disassembled (and commented... far better than MS apparently) most of MS-DOS as a form of personal entertainment, so I actually understand the details quite well... the real issues is whether I actually remember the stuff or not though.

**Comment by neozeed** [comment]
@darrenstarr  there is the "io" part of the Seattle computer products on bitsavers to help fill in the void.

http://bitsavers.trailing-edge.com/bits/SeattleComputerProducts/MSDOS2_FILES/

I've built command.com, edlin and debug so far.

**Comment by darrenstarr** [comment]
@neozeed I think that Microsoft will probably not invest too heavily in this repository so I can't imagine them hosting a merged version. Also, there's a chance that Seattle Computer files haven't been properly "cleaned" for release under MIT.

Sounds like you're having fun though! I'm currently busy fighting with getting Yocto Linux to build... I love "simple to use OS build systems" which make it a nightmare to compile your stuff ;)

**Comment by lenucksi** [comment]
I've actually written a longer document on these published sources that also deals with the details of the boot process. 
I'll get in contact with @bitcrazed to see if there's interest in adding it here.

**Comment by lenucksi** [comment]
@darrenstarr: It's actually a large bunch of LaTeX, I'm not sure that there's a decent, working transpiler to Markdown.

**Comment by bitcrazed** [comment]
There's a lot of pre-existing material out there that documents the PC bootup sequence in far more detail than we can here.

@lenucksi You may have some luck using [Pandoc](http://pandoc.org/) to convert your LaTeX to MD.
