### ISSUE TITLE
Change Copyright for the Community

### ISSUE THREAD

**Issue by blackcrack** [Microsoft/MS-DOS#20]
Hi,

it cold maybe helpful if all have a possible for a benefit of it.
Maybe a gpl2 or so ..

best regards
Blacky

**Comment by blackcrack** [comment]
all can not know.. well, thank you for hint ..

**Comment by blackcrack** [comment]
who want know more and speak with : 
http://reboot.pro/topic/21853-ms-dos-20-source-code-released/#entry207841

**Comment by blackcrack** [comment]
who want know more and speak with : 
this is the [Forum of the founder of nlite](http://reboot.pro/topic/21853-ms-dos-20-source-code-released/), Nuno Brito 

best regards
Blacky

**Comment by blackcrack** [comment]
who want know more and speak with : 
this is the [Forum of the founder of nlite](http://reboot.pro/topic/21853-ms-dos-20-source-code-released/), Nuno Brito 

best regards
Blacky

**Comment by RoestVrijStaal** [comment]
(A)(L)GPLing the code benefits only the FSF (and believers) and not anyone else. And maybe favourable to some who take the challenge to complete rewrite it to a project with a copycentered license (that is, MIT/BSD-3/Apache-2/ISC/et al).

I'm surprised Microsoft used MIT instead of Microsoft Public License (Ms-PL).

**Comment by bitcrazed** [comment]
The source is already licensed under MIT which is about as liberally open as one can get.
