### ISSUE TITLE
I PROMISE

### ISSUE THREAD

**Issue by snobu** [Microsoft/MS-DOS#23]
I'm printing all this assembly code on heavy paper and i'm gonna use it to bitchslap the next person i hear complaining about JavaScript.

**Comment by joshuashaffer** [comment]
It's very straight forward and reasonably documented code, if you know x86 asm.

**Comment by huytu36** [comment]
Great !!!

**Comment by NLDev** [comment]
Sir, you inspired me to do the same.

**Comment by HACKER-3000** [comment]
https://www.youtube.com/watch?v=FONN-0uoTHI

**Comment by bitcrazed** [comment]
Thanks for sharing, though we do not condone any form of violent debate - I think a far more effective response would simply be to drop said "printout" on a table right next to someone you'd like to make a point to. 

Bonus points if its printed on white & green striped dot matrix paper :)

Closing since this isn't an issue that this project can solve.
