### ISSUE TITLE
Use mountpoints instead of drive letters

### ISSUE THREAD

**Issue by aruiz** [Microsoft/MS-DOS#3]
Can we go back in time and fix 40 years of application incompatibility? Mount points are so much better than drive letters!

Anyhow, hats off for open sourcing DOS.

**Comment by alexsandro-xpt** [comment]
@aruiz  Did you know to change this code to do that( mount points over drive letters )?

**Comment by joshuashaffer** [comment]
The BIOS calls to get and set the current drive are done by drive number. Using letters means you just add the immediate constant "A". Just adding "0" would only give you ten. Anything more complicated would require either a macro or function call in every place that sets up drive access, and this means many more cycles on early 80s computers.

**Comment by alexsandro-xpt** [comment]
@joshuashaffer you told `this means many more cycles on early 80s computers` but how is work at unix-like OS at early 80?

**Comment by VladimirMangos** [comment]
@alexsandro-xpt Unix-like OS in early 80s work not in so small computers as I remember.

**Comment by al45tair** [comment]
FWIW the Atari platform came up with quite a nice solution to this precise problem, back in the day. GEMDOS, the underpinnings of Atari's TOS, was essentially a DOS-compatible API running on top of a PC BIOS-compatible BIOS (to the extent that some function numbers were the same and had identical parameters), albeit running on a Motorola 68K rather than Intel 8086. Anyway, the more advanced variants of TOS (MiNT, MultiTOS and MagiC) squared the circle by creating a U: "drive" that worked like the UNIX filesystem root, with all the other devices mounted off it (and with some other UNIX-like features such as /dev and /proc).

I'd agree with the earlier commentator that, on systems that mainly had removable storage, perhaps with a single (and relatively modestly sized) fixed disk, drive letters or numbers made more sense than mount points, which never really worked very well with removable devices. Yes, automounters improve the situation somewhat — though there's no standard location (some use /mnt, the Mac uses /Volumes, and I've seen plenty of other choices too) or indeed naming convention for the mount points, and when you need to refer to the device as opposed to the files on it, the fact is that getting from the mount point to the device name isn't always that easy.

**Comment by bitcrazed** [comment]
Alas, I used-up all the [Time Crystals](https://www.scientificamerican.com/article/time-crystals-could-be-legitimate-form-perpetual-motion/) to zoom back-n-time to commit the sources at the correct dates ;)

BTW - note that while it's too late to fix this issue with MS-DOS, NTFS in Windows NT has always supported [mounting volumes "in folders"](https://en.wikipedia.org/wiki/NTFS_volume_mount_point).

Closing as there's no further action possible to fix this "issue" ;)
