### ISSUE TITLE
Document release dates

### ISSUE THREAD

**Issue by federico-razzoli** [microsoft/MS-DOS#386]
Please document when these DOS versions were released.

**Comment by adalenv** [comment]
I'm just answered for anyone who is interested

**Comment by denzuko** [comment]
@santec  then how about from the original manuals: 

https://archive.org/details/ms-dos-version-2/page/n3

Copyright 1982 Microsoft

**Comment by santec** [comment]
My point is that the repo should contain this information about itself, so the user doesn't need to search external resources (that could cease to exist) or old issues.

**Comment by adalenv** [comment]
I made a pull request

**Comment by bitcrazed** [comment]
Since this isn't a release archive, but an archive of the sources used to build and subsequently release MS-DOS, I think that the more pertinent dates are related to the source files themselves. In which case, the actual source files contain the most relevant dates, e.g. https://github.com/microsoft/MS-DOS/blob/master/v1.25/source/MSDOS.ASM
